### ISSUE TITLE
Awesome Book: With ES6 Modules.

### ISSUE THREAD

**Issue by maximoortelli** [maximoortelli/Awesome-BookES6#2]
_Awesome Books: With ES6 Modules. In this project, i will restructure my Awesome books app code. The goal is to make it more organized by using modules. I will also practice the ES6 syntax that i have learned. The goal here is to master all of the tools and best practices learned about in previous steps to use them in all Microverse projects and most likely in my future job as well._

**Comment by MarkYegon7** [comment]
Nice project :100:

- Good use of GitHub flow principles.
- Good file structure
